version: '3'
services:
  db:
    image: postgres:11.0-alpine
    volumes:
      - chrity_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  backend:
    build:
      context: ./backend
    command: gunicorn --workers=2 --threads=4 --worker-class=gthread --worker-tmp-dir /dev/shm chrty.wsgi:application --bind 0.0.0.0:$PORT
    volumes:
      - './backend/src/:/src'
      - staticfiles:/src/staticfiles  #shared volume between nginx and backend
    ports:
      - "7070:7070"
    env_file:
      - ./.env
    depends_on:
      - db
  pgadmin:
    image: crunchydata/crunchy-pgadmin4:centos7-10.4-2.0.0
    env_file:
      - pgadmin-env.list
    volumes:
      - pga4volume:/var/lib/pgadmin
    ports:
      - "5050:5050"
volumes:
  chrity_postgres_data:
  pga4volume:
  staticfiles:

