version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build:
      context: ./backend
#      args:
#        http_proxy: $http_proxy
#        https_proxy: $https_proxy
    volumes:
      - './backend/src/:/src'
    command: sh -c "python /src/manage.py makemigrations && python /src/manage.py migrate && python /src/manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  postgres_data: